### ISSUE TITLE
Generating only online bazaars

### ISSUE THREAD

**Issue by Qair** [EdenServer/eden-web#100]
The bazaar functionality is great on the website, but I would love to see it only generator online bazaars within the database. Often when I'm searching for an item, I'll find something around the price I'm looking for it to be on a character that's offline or worse offline and hasn't logged into the server for an extended period if time.

**Comment by Spiffly** [comment]
Whilst i agree with the sentiment here, it is frustrating to have lots of bazaars listed for characters who haven't logged on in a long time, i don't think that functionality should be removed altogether.

I quite often 'keep an eye out' for people coming online who have stuff in their bazaars and are offline. I think if a person was to be offline for an exteneded period of time (a month for example) at that point their bazaar shouldn't show up. I have no idea how feasible this is from a coding perspective however so apologies if it's expecting too much.
