### ISSUE TITLE
Who's Online Default Per Page Count 

### ISSUE THREAD

**Issue by bkesecker** [EdenServer/eden-web#104]
As a temporary measure to reduce the load time of the Who's Online list, I suggest defaulting to 10 entries per page.  I do not find myself using the Who's Online page other than viewing the total count.

Just to note, in the previous incarnation of Eden's website I often used the Who's Online page to check gear of players at certain levels (e.g. finding "NIN55/") so I could build test characters with similar gear.  While I can still do that with the new website, I find it cumbersome because all the results aren't searchable, only up to 250.  Perhaps this could be a separate feature request, but I don't have any good ideas how at this time.

**Comment by JasonHoku** [comment]
Fix here: https://github.com/EdenServer/eden-web/pull/128
