### ISSUE TITLE
Website incorrect displaying Crafting skill

### ISSUE THREAD

**Issue by Zhigen1321** [EdenServer/eden-web#117]
Character: Zhigen

Not properly tracking some of the crafting skills, while some are actually correct.

Did not see another ticket with this but I would be surprised if this was the only character with the problem

**Comment by Zhigen1321** [comment]
Confirmed at least clothcraft and leathercraft do not match actual

Leathercraft actual 58.X - Website showing 0.2
Clothcraft actual 6.X - Website showing 0.2

![image](https://user-images.githubusercontent.com/69597679/90153441-fecd1300-dd56-11ea-9e8c-689a1c4f9f10.png)

**Comment by Zhigen1321** [comment]
![image](https://user-images.githubusercontent.com/69597679/90153599-33d96580-dd57-11ea-9929-fec531820d2e.png)

**Comment by rude-jerk** [comment]
This has been resolved by excluding deleted characters.
