### ISSUE TITLE
Sahagin missed move Hydro Shot removes all hate

### ISSUE THREAD

**Issue by Wanpide** [EdenServer/eden-web#129]
While fighting the Sahagin behind the mythril door in SSG I noticed that when the Sahagin's missed their TP move Hydro shot it erased all hate on the mob and it goes unclaimed.

**Comment by Mozzy4Ever** [comment]
That's a https://github.com/EdenServer/community/issues issue, not a website issue.

**Comment by rude-jerk** [comment]
Like Mozzy posted, this belongs in community/issues. Quickly testing this myself I couldn't reproduce it so I won't just move it there.
