### ISSUE TITLE
Red Mage buffs wear out too fast (solo is annoying / not viable)

### ISSUE THREAD

**Issue by Hestichan** [EdenServer/eden-web#137]
I notice every time I go out to do some soloing as RDM I quickly get tired and leave because I spend most of the time casting and recasting buffs, running out my MP pool, and getting very little done in terms of fighting stuff. All the buffs including Phalanx, Stoneskin, Ice Spikes, enWhatever, etc. all wear out too fast before I can even end a single fight. It's just not worth it until this is all fixed and re-balanced.

**Comment by rude-jerk** [comment]
This belongs in https://github.com/EdenServer/community/issues
This issues list is specific to the website, please remake it there! Thanks.
