### ISSUE TITLE
Spells like Drain and Aspir are not worth casting in many cases.

### ISSUE THREAD

**Issue by Hestichan** [EdenServer/eden-web#138]
I have found that in many situations, the spells Drain and Aspir are too weak in their effect to be worth casting. Particularly Aspir, I'm lucky if I even get back what it cost me to cast it, most of the time, and this is against mobs that register 'too weak' to me. What is the point of casting these expensive spells if they don't even do anything? Might as well just sell them! Why do they exist on Eden? Aspir needs to be draining at least 40-50 MP if not 100+ MP to be worthwhile. Drain needs to be doing the same... not these frequent Drains of 10-15 HP -- what is that about and against too weak mobs?? These spells need serious buffing to be worth using.

**Comment by Far-The-Killer** [comment]
You are posting in the wrong bug tracker. Please post this in https://github.com/EdenServer/community/issues instead.

**Comment by KnowOne134** [comment]
Too bad you can't unequip the spell and sell it
