### ISSUE TITLE
Better info on https://edenxi.com/install

### ISSUE THREAD

**Issue by Mozzy4Ever** [EdenServer/eden-web#151]
I see a lot of people join the discord and ask for code, despite not having the game installed/are AFK/don't use the code immediately. This results in them having to request multiple codes because it expires. 

Would it be possible to have that section of the website explain that you need to have the game completely installed before you ask for a registration code? Preferably also have it mention that the codes expire after 10 minutes and to restart your loader before using it. Those 3 things seem to be the most common reason as to why people come back and have to request another code.

**Comment by 59blargedy** [comment]
resolved in https://github.com/EdenServer/eden-web/pull/168
