### ISSUE TITLE
Missing Bass Meuniere Recipe

### ISSUE THREAD

**Issue by DivoXI** [EdenServer/eden-web#224]
The recipe for Bass Meuniere is currently missing on EdenXI website. It needs to be added.

Bass Meuniere: https://edenxi.com/tools/item/4582
Bass Meuniere +1: https://edenxi.com/tools/item/4346

Bass Meuniere Recipe: https://classicffxi.fandom.com/wiki/Bass_Meuniere
![bass meuniere no recipe](https://user-images.githubusercontent.com/113195784/189385786-7d5b8aba-5006-408a-9c1e-17ff2a8ba6b8.GIF)

**Comment by bliven-was-taken** [comment]
Maybe related to #223 but I'm not entirely sure.

**Comment by DivoXI** [comment]
Negative. There's only one ID for Bass Meuniere and another for Bass Meuniere +1.

**Comment by bliven-was-taken** [comment]
Yes, but nothing that has the item ID in the url has a crafting recipe. All the items that have crafting recipes listed have the item name in the URL. (At least that I have found so far)

The report is really all items with the item ID in the url bar don't have the crafting recipes, only pages that have the name do as far as I can tell.
