### ISSUE TITLE
Hydra Tiara Effect Duration

### ISSUE THREAD

**Issue by Isotazar** [EdenServer/eden-web#267]
Retail wiki says duration last for 3 minutes, upon usage duration is 30 seconds on eden

**Comment by slassen** [comment]
Thanks for reporting your concern. Eden goes off 2017 era values. You can see this duration is correct on Eden’s wiki or via history on the retail wiki:
https://classicffxi.fandom.com/wiki/Hydra_Tiara

Additionally, for game issues you will want to report them on the community repo. This is the website repo. Here is a link to the repo to report game issues. Make sure to provide data that the issue template requests.
https://github.com/EdenServer/community
