### ISSUE TITLE
Online GMs Add To "Characters Online" Count

### ISSUE THREAD

**Issue by bkesecker** [EdenServer/eden-web#3]
If a GM is the only logged in characters, the total players online will be 1.  Should GMs be included in the "Characters Online" count?

**Comment by slassen** [comment]
Fixed by [1a899c8c70f8dd2da9a702096590cbfa376b63a5](https://github.com/EdenServer/eden-web/commit/1a899c8c70f8dd2da9a702096590cbfa376b63a5)
