### ISSUE TITLE
Update to Rules

### ISSUE THREAD

**Issue by Shoruto** [EdenServer/eden-web#5]
Need to add the rest of the Allowed and Not Allowed Software along with additional discord rules that I will decide on and add here.  The full addon list can be found in the Eden-Rules discord channel.  For the software we should split it up into Ashita and Windower software lists as some are exclusive to one or the other.

Discord Rules to add

1) Do not post nudity (Real or cartoon) in ANY channel.  It will be deleted and a Discord wide mute will be given.  Any repeated posting of nudity will result in an immediate ban.

2) If you feel you need to vent about someone or something, send me (Shoruto) a PM instead of posting in public chat.  You will not get in trouble if you send me a PM.

**Comment by bkesecker** [comment]
There are now more verbiage updates when this issue was created.  Cross-reference Discord.
