### ISSUE TITLE
Mobile: Bottom Banner Hides Item Search Results

### ISSUE THREAD

**Issue by bkesecker** [EdenServer/eden-web#58]
3 of the 7 search results are unable to display on mobile browsers Chrome and Edge.

**Comment by danielvarcas** [comment]
Have a fix I'll PR shortly.

**Comment by danielvarcas** [comment]
I don't seem to be able to link PRs and issues but the PR is here:

https://github.com/EdenServer/eden-web/pull/67

**Comment by bkesecker** [comment]
Working in test.
