### ISSUE TITLE
Server Online Status Always Offline

### ISSUE THREAD

**Issue by bkesecker** [EdenServer/eden-web#59]
Despite the game server being online, the website reports offline.

**Comment by PrettyCoolPattern** [comment]
Ensure this variable exists and is set to true in your .env

`MOCK_GAME_SERVER_ONLINE=true`

Additionally, the code that queries the status, pulls from account statuses logged in and does not include gm accounts from that query:

```
router.get('/status', async (req, res) => {
  try {
    let gameServerOnline = false;
    if (process.env.MOCK_GAME_SERVER_ONLINE === 'true') {
      gameServerOnline = true;
    } else {
      const status = await scanner.checkPortStatus(
        process.env.GAME_SERVER_PORT,
        process.env.GAME_SERVER_HOST
      );
      gameServerOnline = status === 'open';
    }

    if (gameServerOnline) {
      const query =
        'SELECT COUNT(*) AS ct FROM accounts_sessions JOIN chars ON accounts_sessions.charid = chars.charid WHERE gmlevel = 0;';
      const online = await req.app.locals.query(query);
      return res.status(200).send(online[0].ct.toString());
    }

    return res.status(400).send();
  } catch (error) {
    console.error(error);
    res.status(404).send();
  }
});
```

**Comment by InoUno** [comment]
You should only be setting `MOCK_GAME_SERVER_ONLINE` to `true` for development purposes.

If the two other variables, `GAME_SERVER_HOST` and `GAME_SERVER_PORT`, are set to point at the targeted game server, it will try to detect if it's up by checking that port. For it to be show as online, there will currently also have to be non-GM characters logged into the server, as @PrettyCoolPattern mentioned.

If it is not able to detect that the game server is online even with that, then we might need to investigate if the `portscanner` library isn't able to check the port status for some reason.

**Comment by bkesecker** [comment]
This 'url' seems to not exist (404), which is why `Eden is offline`
![url](https://user-images.githubusercontent.com/45717129/83898536-0c499980-a725-11ea-8c08-647568d821dc.png)

**Comment by bkesecker** [comment]
This is what I see on the console (many entries):
```json
Listening on port 8080...
Error: connect EADDRNOTAVAIL 127.0.0.1 - Local (0.0.0.0:59605)
    at internalConnect (net.js:913:16)
    at defaultTriggerAsyncIdScope (internal/async_hooks.js:305:12)
    at net.js:1004:9
    at processTicksAndRejections (internal/process/task_queues.js:76:11) {
  errno: 'EADDRNOTAVAIL',
  code: 'EADDRNOTAVAIL',
  syscall: 'connect',
  address: '127.0.0.1'
}
Error: connect EADDRNOTAVAIL 127.0.0.1 - Local (0.0.0.0:59648)
    at internalConnect (net.js:913:16)
    at defaultTriggerAsyncIdScope (internal/async_hooks.js:305:12)
    at net.js:1004:9
    at processTicksAndRejections (internal/process/task_queues.js:76:11) {
  errno: 'EADDRNOTAVAIL',
  code: 'EADDRNOTAVAIL',
  syscall: 'connect',
  address: '127.0.0.1'
}
```

**Comment by InoUno** [comment]
Not sure what's causing that to happen in this case. Could be a firewall or something perhaps.
Would need to debug it in some way, or try different things to figure it out.

**Comment by bkesecker** [comment]
I found that MySQL engine 5.7 doesn't like the `AS online` or `AS isOnline` in accounts.js and chars.js, respectively.  Removing the AS made queries work, but reporting status seems dependent upon the value.
