### ISSUE TITLE
Links after clicking doesn't perform correct action

### ISSUE THREAD

**Issue by Shoruto** [EdenServer/eden-web#62]
After clicking both "download the Eden Installer v4.1" & "alternative download" links it reloads Install page and doesn't open up any file to download.

Also the 4.1 should be adjusted to the latest 5.0.

"our modified bootloader" link  on install page reloads page and doesn't open bootloader file.

**Comment by PrettyCoolPattern** [comment]
This is corrected in my Install Info Updates PR branch

**Comment by bkesecker** [comment]
From my use and testing, I agree this is resolved.  Please reopen if not the case.
