### ISSUE TITLE
Update Discord Rules

### ISSUE THREAD

**Issue by Shoruto** [EdenServer/eden-web#63]
Here is the latest from the Eden Rules page, don't need them all if it's too much.

Discord Rules

⦿ Please be respectful to each other.  Consider this phrase when typing, treat others as you would want to be treated.  You wouldn't want someone yelling at you or belittling you so you don't need to do it to another person.
⦿ Please keep the cursing at a minimum.   Some people prefer not to read constant cursing.  We know sometimes a word or two will slip out in the heat of the moment and that is ok but if it becomes a habit we will go to you in private about it.
⦿ Do not post nudity of any kind.
⦿ Do not give out any personal information in public. If you must send it do so via a PM. There are too many people that will take advantage of this personal information.
⦿ Most importantly we want you all to have fun while you use our discord.  We know you won't agree with everything we implement and that is ok.  We do ask that you follow our rules.  If you feel you won't be able to then we kindly thank you for using our discord and ask you to move on to somewhere else to chat.

These rules may be adjusted at any time

Any attempt evading a mute will result in an immediate ban.

It is at the moderators discretion if a player has crossed the line.  If a Staff or Moderator asks a player to do something, that player needs to follow the request.  If they feel this request is not appropriate, contact Shoruto with a screenshot of the request.

If a player feels a Staff is talking inappropriately to another player, contact Shoruto or Juul with a screenshot of the inappropriate chat.

To make our Discord the best possible it takes a community effort. Our moderators won't be able to see everything so if a player happens to see someone breaking one of our rules or has crossed the line somewhere else, please let a moderator know in a private message with a screenshot of the chat that you feel broke the rule.

**Comment by slassen** [comment]
Addressed in `2c3c5f3988ad199074cdc840f2bbd1e8df7c6cca`
