### ISSUE TITLE
Improvement: Site should still be useable when API is not available

### ISSUE THREAD

**Issue by danielvarcas** [EdenServer/eden-web#9]
Noticed this since I can't access the API currently. The site should still be accessible when the API is not available. Any parts of the site requiring data from the API should, from a UI-perspective, be able to handle situations where data is not available.

**Comment by danielvarcas** [comment]
I'm going to start working on this so that I can get the site running at a basic level even without access to any data from the API.

**Comment by slassen** [comment]
You should be able to use the API locally. It's also open source on this repo. You'll need a `.env` setup.

**Comment by danielvarcas** [comment]
We've got it working, thanks :) And I've made the site usable when the server is down. I will do some work to hide certain sections that don't make sense to show when the server is down, like the tools. This is on my fork, not on this repo yet.
