### ISSUE TITLE
Feature Request: World Status Page

### ISSUE THREAD

**Issue by Aioko** [EdenServer/eden-web#92]
A tab under Tools with zone uptimes/crashes. This is extremely valuable information to know when a zone/cluster crashes in case of certain NM timers, as some reset ToD.  I could see why you don't want this to be public information but would be something nice to have.

**Comment by slassen** [comment]
This is available starting from today’s patch using the in game !uptime command.

**Comment by Aioko** [comment]
Oh I must of missed that, thank you. I would still be nice to see it all on one page instead of running out to a zone to check. But it's definitely nice to have, thanks!

**Comment by slassen** [comment]
Closing this as server crashes are much less common now that the server is more mature.
