### ISSUE TITLE
Eden Discord Icon Mismatch

### ISSUE THREAD

**Issue by bkesecker** [EdenServer/eden-web#98]
Website has ToAU icon, but Discord shows the apple.

**Comment by Shoruto** [comment]
![EdenTest](https://user-images.githubusercontent.com/46944745/85769219-c78f9d80-b6e7-11ea-944e-ab5950d7a2eb.gif)

**Comment by JasonHoku** [comment]
https://github.com/EdenServer/eden-web/pull/121 Should solve this.
